[package]
name = "sylt-compiler"
version = "0.1.0"
edition = "2018"

[lib]
path = "src/compiler.rs"

[dependencies]
sylt-common = { path = "../sylt-common" }
sylt-parser = { path = "../sylt-parser" }
